### PR TITLE
JIT compiler + bugfixes

### PR DESCRIPTION
**Pull request by eh-steve**
This is mostly a rebased commit history of #62, plus the addition of a new `jit` package to allow compiling and loading Go files/packages/text, and recursively resolving their dependencies.

This allows users to build and load arbitrary Go files with any number of imports automatically.

You can simply do:

```go

loadable, err = jit.BuildGoFiles(jit.BuildConfig{}, "./path/to/file1.go", "/path/to/file2.go")
// or
loadable, err = jit.BuildGoPackage(jit.BuildConfig{}, "./path/to/package")
// or
loadable, err = jit.BuildGoText(jit.BuildConfig{}, `
package mypackage

import "encoding/json"

func MyFunc(input []byte) (interface{}, error) {
	var output interface{}
	err := json.Unmarshal(input, &output)
	return output, err
}

`)

if err != nil {
    panic(err)
}

module, symbols, err = loadable.Load()

if err != nil {
    panic(err)
}

MyFunc := symbols["MyFunc"].(func([]byte) (interface{}, error))
result, err := MyFunc([]byte(`{"k":"v"}`))
```

The `jit` package and tests are early on in the commit history to demonstrate the purpose of each subsequent commit in fixing specific tests.

So far, testing has only been on `linux/amd64`, `linux/arm64`, `darwin/amd64`, `darwin/arm64` (Apple M1 silicon), and `windows/amd64` . Once the last few `goloader` bugs are ironed out, I will try to backport these changes for earlier Go versions where possible.

Versions:

| **OS/Arch**        | amd64/+CGo         | arm64/+CGo         | amd64/-CGo         | arm64/-CGo         |
|--------------------|--------------------|--------------------|--------------------|--------------------|
| Linux/go-1.19.4    | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| Darwin/go-1.19.4   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:            | :heavy_check_mark:               |
| Windows/go-1.19.4  | :heavy_check_mark:               | :interrobang:      | :heavy_check_mark:                | :interrobang:      |
| Linux/go-1.18.8    | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| Darwin/go-1.18.8   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:            | :heavy_check_mark:                |
| Windows/go-1.18.8  | :x:                | :interrobang:      | :heavy_check_mark:                | :interrobang:      |
| Linux/go-1.17.13   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.17.13  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.17.13 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.16.15   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.16.15  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.16.15 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.15.15   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.15.15  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.15.15 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.14.15   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.14.15  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.14.15 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.13.15   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.13.15  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.13.15 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.12.17   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.12.17  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.12.17 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.11.13   | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.11.13  | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.11.13 | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.10.8    | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.10.8   | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.10.8  | :x:                | :x:                | :x:                | :x:                |
| Linux/go-1.9.7     | :x:                | :x:                | :x:                | :x:                |
| Darwin/go-1.9.7    | :x:                | :x:                | :x:                | :x:                |
| Windows/go-1.9.7   | :x:                | :x:                | :x:                | :x:                |

### CODE REVIEW

**Comment by pkujhd** [comment]
@eh-steve , thanks.
I will try to Recurrence bugs and fix.

By the way, goloader does not test with cgo and asm.

**Comment by eh-steve** [comment]
> By the way, goloader does not test with cgo and asm.
I appreciate that - my main motivation was getting common packages like `net/http` and `math` to build successfully (which directly or indirectly use CGo/asm), and my fixes do seem to work (as shown in the tests).

Interestingly, after rebasing this onto the new Apple silicon commits in master, the http test now fails (where previously it was passing). I kept this working branch as a reference:
https://github.com/eh-steve/goloader/tree/jit-before-apple-silicon-rebase

**Comment by pkujhd** [comment]
@eh-steve
I try use your jit branch to run go test on jit dir, every test output errors like "jit_test.go:42: still have 17 unresolved external symbols despite building and linking dependencies..."

Could you give me an simple case for TestStackSplit and TestJitPanicRecoveryStackTrace this issue mentioned?
Or tell me how to run your test.

Thx

**Comment by eh-steve** [comment]
What version of Go are you using, how do you run the tests, and which symbols remain unresolved? (I'm using 1.19.3 and it's working fine)

I've made certain core packages forbidden for re-inclusion in the JIT compiler to prevent duplication of certain atomic or runtime packages, are the missing symbols from these forbidden packages?

If so, they just need to be included in the test binary by declaring some global variables which use them.

**Comment by eh-steve** [comment]
Edit: 
Fixed this now

> Some tests are still failing randomly (e.g. `TestStackSplit` and `TestJitPanicRecoveryStackTrace`) due to some outstanding bugs in goloader which still need to be fixed.
> 
> Specifically:
> Things which trigger stack copies/stack splits while a dynamically loaded function is running can cause an incomplete stack unwinding (`fatal error: traceback did not unwind completely`) , possibly because the `g`'s stack pointer was incorrectly incremented twice somewhere, so the unwinding doesn't ever reach the stack start. Unclear whether this is a TLS relocation issue or something else causing the `sp` to be incremented by the same frame size twice when calling dynamic code?
> 
> ### Example:
> ```
> === RUN   TestJitPanicRecoveryStackTrace/BuildGoFiles
> runtime: g808: frame.sp=0xc004befd60 top=0xc004beffe0
> 	stack=[0xc004bec000-0xc004bf0000] n=4 max=2147483647
> fatal error: traceback did not unwind completely
> 
> runtime stack:
> runtime.throw({0x849c62?, 0xc00024e000?})
> 	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fb3f6ffca88 sp=0x7fb3f6ffca58 pc=0x439e7d
> runtime.gentraceback(0x7fb40c71400b?, 0xb94c30?, 0xc00003ef00?, 0x7fb3f6ffce60?, 0x0, 0x0, 0x7fffffff, 0x7fb3f6ffce48, 0x1?, 0x0)
> 	/usr/local/go/src/runtime/traceback.go:561 +0x1385 fp=0x7fb3f6ffcdf8 sp=0x7fb3f6ffca88 pc=0x460d85
> runtime.addOneOpenDeferFrame.func1()
> 	/usr/local/go/src/runtime/panic.go:645 +0x6b fp=0x7fb3f6ffce70 sp=0x7fb3f6ffcdf8 pc=0x43900b
> runtime.systemstack()
> 	/usr/local/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x7fb3f6ffce78 sp=0x7fb3f6ffce70 pc=0x46c269
> 
> goroutine 808 [running]:
> runtime.systemstack_switch()
> 	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc004befb20 sp=0xc004befb18 pc=0x46c200
> runtime.addOneOpenDeferFrame(0x41c3e6?, 0xbac840?, 0xc004befbe8?)
> 	/usr/local/go/src/runtime/panic.go:644 +0x69 fp=0xc004befb60 sp=0xc004befb20 pc=0x438f49
> panic({0x7a6480, 0x8dd510})
> 	/usr/local/go/src/runtime/panic.go:844 +0x112 fp=0xc004befc20 sp=0xc004befb60 pc=0x439792
> command-line-arguments.(*SomeType).callSite4(0xc00027bd20?, {{0x7a6480, 0x8dd510}, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0})
> 	/tmp/file1_1093370123/file4.go:16 +0x25 fp=0xc004befc40 sp=0xc004befc20 pc=0x417352ad
> command-line-arguments.(*SomeType).callSite3(0x4e2e73746e656d75?, {{0x7a6480, 0x8dd510}, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0})
> 	/tmp/file1_1093370123/file3.go:13 +0x50 fp=0xc004befca0 sp=0xc004befc40 pc=0x41735268
> command-line-arguments.(*SomeType).callSite2(0xc000028034?, {{0x7a6480, 0x8dd510}, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0})
> 	/tmp/file1_1093370123/file2.go:11 +0x50 fp=0xc004befd00 sp=0xc004befca0 pc=0x417351f8
> command-line-arguments.(*SomeType).callSite1(0x0?, {{0x7a6480, 0x8dd510}, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0})
> 	/tmp/file1_1093370123/file1.go:7 +0x50 fp=0xc004befd60 sp=0xc004befd00 pc=0x41735188
> created by testing.(*T).Run
> 	/usr/local/go/src/testing/testing.go:1493 +0x35f
> 
> ```

**Comment by eh-steve** [comment]
@pkujhd All tests are passing on my machine now, I think it's ready for review

**Comment by pkujhd** [comment]
> Edit: Fixed this now
> 
> > Some tests are still failing randomly (e.g. `TestStackSplit` and `TestJitPanicRecoveryStackTrace`) due to some outstanding bugs in goloader which still need to be fixed.

how to fixed it? I don't find the code change for goloader.

**Comment by pkujhd** [comment]
@eh-steve 

For commit https://github.com/pkujhd/goloader/pull/66/commits/31f8f2bd0af2c793c20cae1e47c9507343b52b25, the pclntable does not split for adapter golang version < 1.16

 For commit [3cd5a08](https://github.com/pkujhd/goloader/pull/66/commits/3cd5a08266674fa56cecae4569b6e391106b0a8d)， plugin use deduplicate function to deal it, but in goloader it will be lead to far address relocate error on R_ADDROFF & R_METHODOFF.  By modifying read-only memory. used first module type descriptor. it could avoid it, but I worried it will be forbidden on MacOSX. I think maybe the best way are use deduplicate function to deal it  and copy type descriptor with far address relocated from the first module into data segment. (it maybe means a lots of workload, because a far address type descriptor maybe is an interface)

For commit [1f39a49](https://github.com/pkujhd/goloader/pull/66/commits/1f39a494d8d5c0a61a6d0d1888112ef63043aec0), could you give me a test case for recurrence it.

By the way, 
I cannot merge pr because the current version cannot pass all tests. I will wait for the newer commit.

**Comment by pkujhd** [comment]
> I could fix this by forcing the symbols to be included by importing more things in `jit_test.go` if you want? In the meantime it should work with `-c`

it is worked for `go test -c`

**Comment by eh-steve** [comment]
> how to fixed it? I don't find the code change for goloader.

Ah sorry, I rebased and force pushed my branch so it got hidden in the other commits. 

The problem was here in `initLinker()`. The runtime uses zero value offsets of `funcnametab` and `pctab` entries to mean something special (zero offset funcname means empty string, and zero offset pctab entry means an external non-Go function which we can't find stack information for).

The logic inside `runtime/traceback.go` (which is used in lots of places for stack copies etc) will be broken if a function has a zero offset for its `nameoff` or a zero offset for it's `pcsp` entry.

To fix it, I added an 8 byte padding to both of those tables so that valid entries never have an offset of 0.
```go
func initLinker() *Linker {
	linker := &Linker{
		// Pad these tabs out so offsets don't start at 0, which is often used in runtime as a special value for "missing"
		// e.g. runtime/traceback.go and runtime/symtab.go both contain checks like:
		// if f.pcsp == 0 ...
		// and
		// if f.nameoff == 0
		funcnametab:  make([]byte, PtrSize),
		pctab:        make([]byte, PtrSize),
```

**Comment by pkujhd** [comment]
@eh-steve  thanks for your contribute.

About per-linker string container with its own lifecycle. it should not be released when the module unload, because maybe some string already set into the map/array container in firstmodule,  when next code access it, the process will be panic.

**Comment by eh-steve** [comment]
> @eh-steve thanks for your contribute.
> 
> About per-linker string container with its own lifecycle. it should not be released when the module unload, because maybe some string already set into the map/array container in firstmodule, when next code access it, the process will be panic.

Yeah that’s why there’s a separate method to unload the string container, and also why I added the heap string option (which is much nicer to use)

**Comment by eh-steve** [comment]
> I've now added basic native ELF relocs for arm64 and amd64, and that seems to make the CGo test work, I'll try to add the macho equivalent shortly.

Mach-O now added too (tested on both x86 and apple M1 silicon).

**Comment by eh-steve** [comment]
@pkujhd You might also be interested in this bugfix:
https://github.com/pkujhd/goloader/pull/66/commits/b42e18025d406e7b279f1f11adf19ca43900fb05

Previously it was rare, but possible to be pre-empted by the scheduler (or a signal handler) while executing JIT instructions appended to the end of the code segment due to a far address relocation. In these cases, the runtime could throw a fatal error `runtime: invalid pc-encoded table` because the PC addresses don't correspond to any known functions based on `findfuncbucket`s, and they would be missing pcvalues for things like PCSP, PCLine, PCFile, and `PCDATA_UnsafePoint`. This wasn't safe.

I switched to pre-emptively growing the size of any function text which had a potentially overflowing relocation, and reserved an "epilogue" for each relocation to use if needed. Then I patched all the pcvalue tables in order to reflect the correct value for this epilogue PC segment (based on the pcvalue at the relocation site). This seems to have resolved these pre-emption bugs.

**Comment by eh-steve** [comment]
@pkujhd FYI today I started to port some of the missing mprotect and mmap functionality for Windows in this branch https://github.com/eh-steve/goloader/commit/079d833490608d4ce1883081609b84c712d73874

It’s not finished and so doesn’t work properly yet, but just a heads up in case you were interested

**Comment by eh-steve** [comment]
> @pkujhd FYI today I started to port some of the missing mprotect and mmap functionality for Windows in this branch [eh-steve@079d833](https://github.com/eh-steve/goloader/commit/079d833490608d4ce1883081609b84c712d73874)
> 
> It’s not finished and so doesn’t work properly yet, but just a heads up in case you were interested

@pkujhd I finished this off today so most of the JIT tests pass on Windows now (and it solves previous problematic method relocations overflowing due to the distance being >32 bit), but proper CGo support on Windows is still missing, and I'm unlikely to invest time in adding it (because 🪟 💩).

Also, the `TestJitHttpGet` test currently fails on Windows with `all goroutines are asleep - deadlock` which I haven't investigated properly.

I'm also unlikely to invest much more time in backporting changes to older versions of Go... Is this something you feel is critical for the project?

**Comment by eh-steve** [comment]
> > I'm also unlikely to invest much more time in backporting changes to older versions of Go... Is this something you feel is critical for the project?
> 
> 
> 
> because some related online projects still use golang 1.16 even golang 1.11.

Ok, what do you think about tagging the 0.0.17 release as the last version supporting Go < 1.18, and directing people to use that version if they need older versions of Go?

**Comment by pkujhd** [comment]
@eh-steve 
I will take the time to merge this branch into the trunk and try to adapt to the lower versions of Golang,
I think we should separate a new repos from the part of code（package jit) that provides compilation obj file, which is of a tool.
I will not consider ending the support of the lower version of golang, because there are still many bugs in the current version. Consider maintaining a new repos when golang 2.0

**Comment by eh-steve** [comment]
I wish you would not reimplement parts of my commits manually as it makes it very difficult to rebase and resolve conflicts, unless you plan to repeat the  implementation of the entire PR by hand?

If this is the case, I might just hard fork and maintain a separate repo...

I don't mind splitting the JIT package into a separate repo, but the tests there have exposed maybe ~20 or so bugs in goloader and provides a nice test base when porting for new Go versions or architectures.

**Comment by pkujhd** [comment]
@eh-steve I suggest you have a hard fork if you want make it work on golang version two major versions and  with cgo. 

I don't have enough to read all golang's linker，so I worry more complex mechanism to lead more unknown question.

online project use it on linux/amd64 and mmap on <4G address, avoid rewrite machine code as far as possible

In addition, thanks for fixing various bugs.

**Comment by eh-steve** [comment]
Also I think you force pushed stuff to master?

**Comment by pkujhd** [comment]
> Also I think you force pushed stuff to master?

I will block master branch before merge it， and try to merge it and split package. but i will take some time.

**Comment by eh-steve** [comment]
There's still some broken things in Go 1.20 which I'm fixing - `inlinedCall` struct has changed size which isn't in master yet - I might be force pushing the last commit on this branch a few times while I fix the remaining tests for 1.20.

I meant that you had force pushed onto master which means any branches off master would have conflicts, and that it's generally not a good idea to force push onto master without careful coordination with other contributors.

I think you and I have a different understanding of "merge"...

**Comment by pkujhd** [comment]
@eh-steve ，
 I suggest you have a hard fork, because When I merge you jit branch and try to adapter lower golang version， I find it very difficult. 
I will merge your bug fixed into the trunk. 
Thank you for your contribution.

**Comment by eh-steve** [comment]
Yeah I hard forked in https://github.com/pkujhd/goloader/pull/66/commits/e0dbc397477f5f6955a87a344b8539d40f188175

**Comment by eh-steve** [comment]
> I will merge your bug fixed into the trunk.

I'd be curious how you plan to address the incorrect cuFiles and cuOffsets after the pclntab separation causing broken stack traces

**Comment by pkujhd** [comment]
> I'd be curious how you plan to address the incorrect cuFiles and cuOffsets after the pclntab separation causing broken stack traces

In the current version, there is a problem with the filling of ftab. If the loader does not use cuOffsets in the lower version of golang, the loader need to modify the PCFile. In the higher version of golang, cuOffsets exist. the loader can fill cuOffsets to avoid this problem，but still read PCFile

this problem lead to your testcase TestJitPanicRecoveryStackTrace failed

**Comment by pkujhd** [comment]
> I'd be curious how you plan to address the incorrect cuFiles and cuOffsets after the pclntab separation causing broken stack traces

I guess what you mean is the error of PCFile. 
There is an error in the previous version. 

In the Golang<1.16 version, It leads to the function which isn't in the first .obj file has not correct offset of the fileno.
In version>=1.16, the funcfile function will be panic

In the version of golang<1.16 PCFile will be rewritten by linker,
In the version of>=1.16, linker uses cuOffset to deal it

I'm going to use a similar scheme to avoid mistakes

**Comment by pkujhd** [comment]
The current master version has basically completed the support for cgo.
For the tls problem, it should only appears in the -dynlink compilation mode of Linux. 
Currently, for linux/amd64,  the goloaderbuilder does not generate position-independce-code,  generates position-independce-code on windows/mac platform.
For the duplicate type problem, the current version defaults to using the type in the original running environment, and adds fake itab through interface detection to avoid panic with unreachable code. This solution should be safer than directly modifying the read-only memory of the runtime in your fork.
In addition, on the x86 platform, in order to reduce the problems caused by modifying the machine code, golang/x/arch/x86/x86asm is used to decode machine code and mark the instruction boundary.

So I will close this pull reqeust.

Thank you for your contribute.

There are still some remaining issues. There is no good solution to the initialization problem of the current high golang version(>=1.21). The golang linker uses the compiler to assist in trimming the initialization function to versions >= 1.21.
